### ISSUE TITLE
パーソナルデータ連携モジュール　ビルド手順書のUnit Testが正常終了しない

### ISSUE THREAD

**Issue by mizu-bs** [Personal-Data-Linkage-Module/pxr-linkage#68]
以下のページで公開されているパーソナルデータ連携モジュールのビルド手順書に従って環境構築を行っていますが、
以下①②の現象が発生しています。
対応策についてご存じの方がいらっしゃいましたらご教示いただけますと幸いです。

https://data-society-alliance.org/area-data/module/manual/
パーソナルデータ連携モジュール　ビルド手順書(2022/11/30版)

■現象①
ビルド手順書_pxr-access-control-manage-service.pdfについて、
「3.3 Unit Testを実行する」に記載されている以下のコマンドの実行後、エラーが出力されます。
エラーを解消するための対応策を教えていただけないでしょうか。

<実行したコマンド>
npm run test:unit

<エラー内容>
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of XMLElement
    at Object.writeFile (node:fs:2271:5)
    at /root/work/repo/pxr-access-control-manage-service/node_modules/jest-html-reporter/dist/main.js:47:13
    at /root/work/repo/pxr-access-control-manage-service/node_modules/jest-html-reporter/node_modules/mkdirp/index.js:48:26
    at FSReqCallback.oncomplete (node:fs:211:5)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)

■現象②
ビルド手順書_pxr-access-control-service.pdfについて、
「3.3 Unit Testを実行する」に記載されている以下のコマンドの実行後、処理が進行していないように見えます。
当事象を解消するための対応策を教えていただけますでしょうか。

<実行したコマンド>
npm run test:unit

<コマンド実行後の出力内容>
> access-control-service@1.0.0 test:unit
> jest --coverage --forceExit --detectOpenHandles --runInBand --config=jest.unit.config.js
 RUNS  src/tests/01-01.Token.spec.ts

→上記のRUNS～の行が表示された状態から時間が経過しても変化がない状態です。

**Comment by mizu-bs** [comment]
事象の内容について要確認事項があるためクローズ
